{{- $platformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-oneagent-operator.platformSet" .))}}
{{- if eq .Values.platform "kubernetes" }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-oneagent
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-oneagent
    verbs:
      - use
{{ end }}
