# Default values for dynatrace-oneagent-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

platform: ""

operator:
  image: "quay.io/dynatrace/dynatrace-oneagent-operator:snapshot"

oneagent:
  name: "oneagent"
  apiUrl:

secret:
  name: "oneagent"
  apiToken:
  paasToken: