{{- $platformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-oneagent-operator.platformSet" .))}}
{{- if eq .Values.platform "openshift" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-oneagent-operator
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: redhat-connect
  - name: redhat-connect-sso
{{ end }}
