apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-oneagent-operator.commonlabels" . | nindent 4 }}
spec:
  descriptor:
    type: "Dynatrace OneAgent Operator"
    version: "0.1.0"
    maintainers:
      - name: Dynatrace LLC
        url: https://www.dynatrace.com/
    keywords:
      - "dynatrace"
      - "operator"
      - "oneagent"
      - "k8s"
      - "monitoring"
      - "apm"
    description: |
      The Dynatrace OneAgent Operator allows users to easily deploy full-stack monitoring for [Kubernetes clusters](https://www.dynatrace.com/technologies/kubernetes-monitoring/). The Dynatrace OneAgent automatically monitors the workload running in containers down to the code and request level.

      ### Installing the OneAgent
      Once you've installed the Operator, you can create OneAgent custom resources to monitor your environment.

      First, please add a Secret within the Project you've deployed the Dynatrace Operator to, which would contain your API and PaaS tokens. Create tokens of type *Dynatrace API* (`API_TOKEN`) and *Platform as a Service* (`PAAS_TOKEN`) and use their values in the following commands respectively.

      For assistance please refer to [Create user-generated access tokens](https://www.dynatrace.com/support/help/shortlink/token#create-user-generated-access-tokens).

      ``` $ oc -n <project> create secret generic oneagent --from-literal="apiToken=API_TOKEN" --from-literal="paasToken=PAAS_TOKEN" ```

      You may update this Secret at any time to rotate the tokens.

      Then please add an OneAgent object in the Project where the Operator has been deployed, configured to your needs.

      ### Required Parameters
      * `apiUrl` - provide the URL to the API of your Dynatrace environment. In Dynatrace SaaS it will look like `https://<ENVIRONMENTID>.live.dynatrace.com/api` . In Dynatrace Managed like `https://<YourDynatraceServerURL>/e/<ENVIRONMENTID>/api` .

      ### Advanced Options
      * **Image Override** - use a copy of the OneAgent container image from a registry other than Docker's or Red Hat's
      * **NodeSelectors** - select a subset of your cluster's nodes to run the Dynatrace OneAgent on, based on labels
      * **Tolerations** - add specific tolerations to the agent so that it can monitor all of the nodes in your cluster; we include the default toleration so that Dynatrace OneAgent also monitors the master nodes
      * **Priority Class Name** - define the priorityClassName for OneAgent pods
      * **Environment variables** - define environment variables for the OneAgent container
      * **Disable Certificate Checking** - disable any certificate validation that may interact poorly with proxies with in your cluster
      * **Disable OneAgent Update** - disable the Operator's auto-update feature for OneAgent pods
      * **Enable Istio Auto-config** - automatically create Istio objects for egress communication to the Dynatrace environment from the OneAgent

      For a complete list of supported parameters please consult the [Operator Deploy Guide](https://www.dynatrace.com/support/help/shortlink/kubernetes-deploy).
    icons:
      - src: "https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png"
        type: "image/png"
    links:
      - description: Dynatrace Website
        url: https://www.dynatrace.com/
      - description: Operator Deploy Guide
        url: https://www.dynatrace.com/support/help/shortlink/kubernetes-deploy
      - description: Kubernetes Monitoring Info
        url: https://www.dynatrace.com/technologies/kubernetes-monitoring
