apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  apiToken: {{ .Values.secret.apiToken | b64enc }}
  paasToken: {{ .Values.secret.paasToken | b64enc }}
type: Opaque
